export type OptionsListData = {
  id: number | string
  name: string
  models?: string[]
}

export const OptionsList: OptionsListData[] = [
  { id: 1, name: 'AC', models: ['378 GT Zagato', 'Ace', 'Aceca', 'Cobra'] },
  { id: 2, name: 'Acura', models: ['MDX', 'RDX', 'NSX', 'TLX', 'ILX', 'RLX'] },
  { id: 3, name: 'Alfa Romeo', models: ['Giulia', 'Stelvio', '4C', 'Giulietta', 'Spider', 'Brera'] },
  { id: 4, name: 'Alpine', models: ['A110'] },
  { id: 5, name: 'AM General', models: ['Humvee', 'Hummer H1'] },
  { id: 6, name: 'Ariel', models: ['Atom'] },
  { id: 7, name: 'Aro', models: ['240', '244'] },
  { id: 8, name: 'Asia', models: ['Rocsta', 'Towner'] },
  { id: 9, name: 'Aston Martin', models: ['DB11', 'Vantage', 'DBS Superleggera', 'Rapide', 'Valhalla'] },
  { id: 10, name: 'Audi', models: ['A4', 'A6', 'Q5', 'Q7', 'R8', 'TT', 'A8', 'S5'] },
  { id: 11, name: 'Austin', models: ['Mini', 'Healey 3000', 'Austin 7', 'Maestro', 'Montego'] },
  { id: 12, name: 'Autobianchi', models: ['A112', 'Y10', 'Primula'] },
  { id: 13, name: 'Baltijas Dzips', models: ['BD-132', 'BD-11'] },
  { id: 14, name: 'Beijing', models: ['Senova D70', 'X3', 'E-series'] },
  { id: 15, name: 'Bentley', models: ['Continental GT', 'Bentayga', 'Mulsanne', 'Flying Spur'] },
  { id: 16, name: 'Bertone', models: ['Mantide', 'Stratos Zero', 'Genesis'] },
  { id: 17, name: 'Bitter', models: ['SC', 'Vero', 'CD'] },
  { id: 18, name: 'BMW', models: ['3 Series', '5 Series', '7 Series', 'X5', 'M3', 'M5', 'i8', 'Z4'] },
  { id: 19, name: 'BMW Alpina', models: ['B7', 'B3', 'B6', 'B4'] },
  { id: 20, name: 'Brabus', models: ['850 6.0 Biturbo', 'Rocket 900', 'B63S-700', 'G800', 'Maybach 900'] },
  { id: 21, name: 'Brilliance', models: ['BS4', 'BS6', 'V5', 'H330', 'H230'] },
  { id: 22, name: 'Bristol', models: ['Bullet', 'Fighter', 'Blenheim', '410', '411'] },
  { id: 23, name: 'Bufori', models: ['La Joya', 'Geneva', 'BMS R1', 'MK VI', 'BMS R2'] },
  { id: 24, name: 'Bugatti', models: ['Chiron', 'Veyron', 'Centodieci', 'Divo', 'La Voiture Noire'] },
  { id: 25, name: 'Buick', models: ['Encore', 'Envision', 'Regal', 'LaCrosse', 'Enclave'] },
  { id: 26, name: 'BYD', models: ['Tang', 'Han', 'Song Plus', 'Yuan', 'e2'] },
  { id: 27, name: 'Byvin', models: ['B3', 'B6', 'B8', 'F6', 'M3'] },
  { id: 28, name: 'Cadillac', models: ['Escalade', 'XT5', 'CT5', 'CT6', 'ATS', 'CTS'] },
  { id: 29, name: 'Callaway', models: ['Corvette C7 Aerowagen', 'C16', 'C12', 'C7 GT3-R'] },
  { id: 30, name: 'Carbodies', models: ['Fairway', 'FX4', 'Taxi', 'Sherpa'] },
  { id: 31, name: 'Caterham', models: ['Seven 620R', 'Superlight R500', 'Seven 310', 'Seven 485'] },
  { id: 32, name: 'Changan', models: ['CS35 Plus', 'CS75 Plus', 'Eado XT', 'Alsvin V7', 'Uni-K'] },
  { id: 33, name: 'ChangFeng', models: ['Liebao CS6', 'CS7', 'CS9', 'CS35', 'CS75'] },
  { id: 34, name: 'Chery', models: ['Tiggo 8', 'Arrizo 5', 'QQ', 'Fulwin 2', 'Arrizo GX'] },
  { id: 35, name: 'Chevrolet', models: ['Silverado', 'Camaro', 'Equinox', 'Malibu', 'Traverse', 'Blazer'] },
  { id: 36, name: 'Chrysler', models: ['300', 'Pacifica', 'Voyager', 'Aspen'] },
  { id: 37, name: 'Citroen', models: ['C3', 'C4 Cactus', 'C5 Aircross', 'Berlingo', 'Spacetourer'] },
  { id: 38, name: 'Cizeta', models: ['V16T'] },
  { id: 39, name: 'Coggiola', models: ['T-Rex', 'Tuchmann', 'Supercar'] },
  { id: 40, name: 'Dacia', models: ['Duster', 'Sandero', 'Logan', 'Dokker', 'Lodgy'] },
  { id: 41, name: 'Dadi', models: ['City Leading', 'Shuttle', 'Smoothing A+', 'City Universe'] },
  { id: 42, name: 'Daewoo', models: ['Matiz', 'Lanos', 'Nexia', 'Espero', 'Kalos', 'Magnus'] },
  { id: 43, name: 'DAF', models: ['XF', 'CF', 'LF', '95', '75'] },
  { id: 44, name: 'Daihatsu', models: ['Terios', 'Sirion', 'Mira', 'Cuore', 'Move', 'Copen'] },
  { id: 45, name: 'Daimler', models: ['Smart EQ Fortwo', 'Smart EQ Forfour', 'Mercedes-Maybach S-Class'] },
  { id: 46, name: 'Dallas', models: ['Impostor', 'Phantom', 'Maverick', 'Meitaro', 'Arbel'] },
  { id: 47, name: 'Datsun', models: ['GO', 'Cross', 'on-DO', 'mi-DO', 'redi-GO'] },
  { id: 48, name: 'De Tomaso', models: ['Pantera', 'Mangusta', 'Guara', 'Longchamp', 'Vallelunga'] },
  { id: 49, name: 'DeLorean', models: ['DMC-12'] },
  { id: 50, name: 'Derways', models: ['Aurora', 'Plutus', 'Tiggo', 'Salam', 'Shuttle'] },
  { id: 51, name: 'Dodge', models: ['Charger', 'Challenger', 'Durango', 'Journey', 'Viper', 'Ram'] },
  { id: 52, name: 'DongFeng', models: ['AX7', 'X30', 'Joyear', 'S30', 'H30 Cross'] },
  { id: 53, name: 'Doninvest', models: ['Orion', 'Assol', 'Kondor', 'Impuls', 'Orion-M1'] },
  { id: 54, name: 'Donkervoort', models: ['D8 GTO', 'D8 GTO-JD70', 'D8 GTO-RS', 'D8 GTO Bilster Berg Edition'] },
  { id: 55, name: 'E-Car', models: ['2CV Electric', 'e-Berlingo Multispace', 'e-Mehari'] },
  { id: 56, name: 'Eagle', models: ['Vision', 'Talon', 'Premier', 'Summit'] },
  { id: 57, name: 'Eagle Cars', models: ['SSC Ultimate Aero', 'SSC Tuatara'] },
  { id: 58, name: 'Ecomotors', models: ['OPOC Engine'] },
  { id: 59, name: 'FAW', models: ['Besturn B50', 'Besturn X40', 'Besturn X80', 'V2', 'V5'] },
  { id: 60, name: 'Ferrari', models: ['F8 Tributo', '488 GTB', '812 Superfast', 'Roma', 'SF90 Stradale'] },
  { id: 61, name: 'Fiat', models: ['500', 'Panda', 'Tipo', '500X', '124 Spider', 'Ducato'] },
  { id: 62, name: 'Fisker', models: ['Karma', 'Ocean'] },
  { id: 63, name: 'Ford', models: ['F-150', 'Mustang', 'Focus', 'Explorer', 'Escape', 'Ranger', 'Expedition'] },
  { id: 64, name: 'Foton', models: ['Tunland', 'Sauvana', 'View', 'Thunder'] },
  { id: 65, name: 'FSO', models: ['Polonez', 'Caro', 'Atu'] },
  { id: 66, name: 'Fuqi', models: ['Conqueror'] },
  { id: 67, name: 'Geely', models: ['Coolray', 'Emgrand X7', 'Atlas', 'Binrui', 'Bo Rui', 'Xing Yue'] },
  { id: 68, name: 'Geo', models: ['Metro', 'Prizm', 'Tracker'] },
  { id: 69, name: 'GMC', models: ['Sierra', 'Canyon', 'Terrain', 'Yukon', 'Acadia'] },
  { id: 70, name: 'Gonow', models: ['GX6', 'Troy'] },
  { id: 71, name: 'Great Wall', models: ['Haval H6', 'Haval H9', 'Wingle 5', 'Coolbear', 'Deer'] },
  { id: 72, name: 'Hafei', models: ['Lobo', 'Saibao', 'Zhongyi'] },
  { id: 73, name: 'Haima', models: ['7X', 'Family', 'M3', 'M6', 'S5'] },
  { id: 74, name: 'Hindustan', models: ['Ambassador', 'Contessa'] },
  { id: 75, name: 'Holden', models: ['Commodore', 'Trailblazer', 'Colorado', 'Astra'] },
  { id: 76, name: 'Honda', models: ['Civic', 'Accord', 'CR-V', 'Pilot', 'Fit', 'HR-V'] },
  { id: 77, name: 'HuangHai', models: ['Plutus', 'Landscape'] },
  { id: 78, name: 'Hummer', models: ['H1', 'H2', 'H3'] },
  { id: 79, name: 'Hyundai', models: ['Elantra', 'Sonata', 'Tucson', 'Santa Fe', 'Kona', 'Palisade'] },
  { id: 80, name: 'Infiniti', models: ['Q50', 'Q60', 'QX50', 'QX60', 'QX80'] },
  { id: 81, name: 'Innocenti', models: ['Mini', 'Elba', 'Small'] },
  { id: 82, name: 'Invicta', models: ['S1'] },
  { id: 83, name: 'Iran Khodro', models: ['Runna', 'Dena', 'Soren', 'Samand'] },
  { id: 84, name: 'Isdera', models: ['Commendatore 112i'] },
  { id: 85, name: 'Isuzu', models: ['D-Max', 'Trooper', 'MUX'] },
  { id: 86, name: 'IVECO', models: ['Daily', 'Stralis', 'Eurocargo'] },
  { id: 87, name: 'JAC', models: ['J3', 'J5', 'S2', 'S3', 'T6'] },
  { id: 88, name: 'Jaguar', models: ['F-Pace', 'XE', 'XF', 'XJ', 'I-Pace'] },
  { id: 89, name: 'Jeep', models: ['Grand Cherokee', 'Wrangler', 'Cherokee', 'Compass', 'Renegade'] },
  { id: 90, name: 'Jensen', models: ['Interceptor', 'Healey'] },
  { id: 91, name: 'JMC', models: ['Boarding'] },
  { id: 92, name: 'Kia', models: ['Sorento', 'Sportage', 'Telluride', 'Soul', 'Rio', 'Forte'] },
  { id: 93, name: 'Koenigsegg', models: ['Jesko', 'Gemera', 'Regera'] },
  { id: 94, name: 'KTM', models: ['X-Bow'] },
  { id: 95, name: 'Lamborghini', models: ['Huracan', 'Aventador', 'Urus'] },
  { id: 96, name: 'Lancia', models: ['Ypsilon', 'Delta', 'Thema'] },
  { id: 97, name: 'Land Rover', models: ['Range Rover', 'Discovery', 'Defender', 'Velar', 'Evoque'] },
  { id: 98, name: 'Landwind', models: ['X7', 'X5'] },
  { id: 99, name: 'Lexus', models: ['RX', 'NX', 'IS', 'LS', 'GX', 'LX'] },
  { id: 100, name: 'Liebao Motor', models: ['CS7', 'Domy X5', 'Domy X7', 'C3'] },
  { id: 101, name: 'Lifan', models: ['X60', 'Myway', 'X50', 'X80', 'X70'] },
  { id: 102, name: 'Lincoln', models: ['Navigator', 'Aviator', 'Corsair', 'Continental'] },
  { id: 103, name: 'Lotus', models: ['Evora', 'Exige', 'Elise'] },
  { id: 104, name: 'LTI', models: ['TX4'] },
  { id: 105, name: 'Luxgen', models: ['U6 Turbo', 'S3', 'M7'] },
  { id: 106, name: 'Mahindra', models: ['Thar', 'Scorpio', 'XUV500', 'Bolero'] },
  { id: 107, name: 'Marcos', models: ['Mantis', 'TSO'] },
  { id: 108, name: 'Marlin', models: ['Sportster'] },
  { id: 109, name: 'Marussia', models: ['B1', 'B2'] },
  { id: 110, name: 'Maruti', models: ['Swift', 'Baleno', 'Vitara Brezza', 'Dzire', 'S-Cross'] },
  { id: 111, name: 'Maserati', models: ['Ghibli', 'Quattroporte', 'Levante', 'GranTurismo'] },
  { id: 112, name: 'Maybach', models: ['S-Class', 'GLS'] },
  { id: 113, name: 'Mazda', models: ['Mazda3', 'Mazda6', 'CX-5', 'MX-5', 'CX-9'] },
  { id: 114, name: 'McLaren', models: ['720S', '570S', 'GT'] },
  { id: 115, name: 'Mega', models: ['Club', 'Track'] },
  { id: 116, name: 'Mercedes-Benz', models: ['C-Class', 'E-Class', 'S-Class', 'GLC', 'GLE', 'GLA'] },
  { id: 117, name: 'Mercury', models: ['Grand Marquis', 'Milan', 'Sable'] },
  { id: 118, name: 'Metrocab', models: ['TTT'] },
  { id: 119, name: 'MG', models: ['MG3', 'MG ZS', 'MG Hector'] },
  { id: 120, name: 'Microcar', models: ['M.Go', 'Dué'] },
  { id: 121, name: 'Minelli', models: ['Transit'] },
  { id: 122, name: 'Mini', models: ['Cooper', 'Countryman', 'Clubman', 'Convertible', 'Paceman'] },
  { id: 123, name: 'Mitsubishi', models: ['Outlander', 'Eclipse Cross', 'Pajero', 'L200', 'ASX'] },
  { id: 124, name: 'Mitsuoka', models: ['Galue', 'Orochi', 'Viewt', 'Ryugi'] },
  { id: 125, name: 'Morgan', models: ['Plus Four', 'Plus Six', '3 Wheeler'] },
  { id: 126, name: 'Morris', models: ['Minor', 'Marina'] },
  { id: 127, name: 'Nissan', models: ['Altima', 'Rogue', 'Titan', 'Pathfinder', 'Armada', '370Z'] },
  { id: 128, name: 'Noble', models: ['M600'] },
  { id: 129, name: 'Oldsmobile', models: ['Cutlass', '88', 'Alero'] },
  { id: 130, name: 'Opel', models: ['Astra', 'Insignia', 'Corsa', 'Mokka', 'Grandland X'] },
  { id: 131, name: 'Osca', models: ['1600 GT'] },
  { id: 132, name: 'Pagani', models: ['Huayra', 'Zonda'] },
  { id: 133, name: 'Panoz', models: ['Esperante'] },
  { id: 134, name: 'Perodua', models: ['Myvi', 'Bezza', 'Axia'] },
  { id: 135, name: 'Peugeot', models: ['308', '208', '3008', '5008', '2008'] },
  { id: 136, name: 'Piaggio', models: ['Ape', 'Porter'] },
  { id: 137, name: 'Plymouth', models: ['Barracuda', 'Road Runner', 'Fury'] },
  { id: 138, name: 'Pontiac', models: ['GTO', 'Firebird', 'Grand Prix', 'Vibe'] },
  { id: 139, name: 'Porsche', models: ['911', 'Cayenne', 'Panamera', 'Macan', 'Taycan'] },
  { id: 140, name: 'Premier', models: ['Rio', '118 NE'] },
  { id: 141, name: 'Proton', models: ['Saga', 'Persona', 'X70'] },
  { id: 142, name: 'PUCH', models: ['G-Modell'] },
  { id: 143, name: 'Puma', models: ['GT'] },
  { id: 144, name: 'Qoros', models: ['Q3', 'Q5'] },
  { id: 145, name: 'Qvale', models: ['Mangusta'] },
  { id: 146, name: 'Reliant', models: ['Robin'] },
  { id: 147, name: 'Renault', models: ['Clio', 'Megane', 'Captur', 'Kadjar', 'Duster'] },
  { id: 148, name: 'Renault Samsung', models: ['SM6', 'QM6'] },
  { id: 149, name: 'Rolls-Royce', models: ['Phantom', 'Cullinan', 'Ghost', 'Wraith'] },
  { id: 150, name: 'Ronart', models: ['Lightning'] },
  { id: 151, name: 'Rover', models: ['75', 'Range Rover Evoque'] },
  { id: 152, name: 'Saab', models: ['9-3', '9-5', '900'] },
  { id: 153, name: 'Saleen', models: ['S7'] },
  { id: 154, name: 'Santana', models: ['300', 'Anibal'] },
  { id: 155, name: 'Saturn', models: ['Vue', 'Sky'] },
  { id: 156, name: 'Scion', models: ['tC', 'xA', 'xB', 'FR-S'] },
  { id: 157, name: 'SEAT', models: ['Leon', 'Ibiza', 'Ateca', 'Arona', 'Tarraco'] },
  { id: 158, name: 'ShuangHuan', models: ['CEO'] },
  { id: 159, name: 'Skoda', models: ['Octavia', 'Superb', 'Kodiaq', 'Karoq', 'Scala'] },
  { id: 160, name: 'Smart', models: ['Fortwo', 'Forfour'] },
  { id: 161, name: 'Soueast', models: ['DX7', 'DX3', 'V5'] },
  { id: 162, name: 'Spectre', models: ['R42'] },
  { id: 163, name: 'Spyker', models: ['C8', 'C12'] },
  { id: 165, name: 'Ssang Yong', models: ['Rexton', 'Korando', 'Tivoli', 'Musso', 'Actyon'] },
  { id: 166, name: 'Subaru', models: ['Outback', 'Forester', 'Impreza', 'Legacy', 'Crosstrek', 'WRX'] },
  { id: 167, name: 'Suzuki', models: ['Swift', 'Vitara', 'Jimny', 'S-Cross', 'Baleno', 'Ignis'] },
  { id: 168, name: 'Talbot', models: ['Horizon', 'Solara'] },
  { id: 169, name: 'TATA', models: ['Harrier', 'Nexon', 'Altroz', 'Tiago', 'Safari'] },
  { id: 170, name: 'Tatra', models: ['T813', 'T815', 'Phoenix'] },
  { id: 171, name: 'Tazzari', models: ['Zero'] },
  { id: 172, name: 'Tesla', models: ['Model S', 'Model 3', 'Model X', 'Model Y', 'Cybertruck', 'Roadster'] },
  { id: 173, name: 'Tianma', models: ['Century', 'Jing Lun'] },
  { id: 174, name: 'Tianye', models: ['Sovereign'] },
  { id: 175, name: 'Tofas', models: ['Sahin', 'Dogan', 'Kartal', 'Serce'] },
  { id: 176, name: 'Toyota', models: ['Camry', 'Corolla', 'Rav4', 'Highlander', 'Prius', 'Land Cruiser'] },
  { id: 177, name: 'Trabant', models: ['601', '1.1', '1.1 Universal'] },
  { id: 178, name: 'Tramontana', models: ['XTR'] },
  { id: 179, name: 'Triumph', models: ['TR6', 'Spitfire', 'GT6', 'Dolomite', 'Stag'] },
  { id: 180, name: 'TVR', models: ['Griffith', 'Cerbera', 'Tuscan', 'Sagaris'] },
  { id: 181, name: 'Vauxhall', models: ['Astra', 'Corsa', 'Insignia', 'Mokka', 'Crossland', 'Grandland'] },
  { id: 182, name: 'Vector', models: ['W8', 'M12'] },
  { id: 183, name: 'Venturi', models: ['Atlantique', '400 GT', 'Fetish'] },
  { id: 184, name: 'Volkswagen', models: ['Golf', 'Passat', 'Tiguan', 'Atlas', 'Jetta', 'Arteon'] },
  { id: 185, name: 'Volvo', models: ['XC90', 'XC60', 'S60', 'V60', 'XC40', 'S90'] },
  { id: 186, name: 'Vortex', models: ['Tingo', 'Estina'] },
  { id: 187, name: 'Wartburg', models: ['311', '353', '1.3'] },
  { id: 188, name: 'Westfield', models: ['SE', 'Sport Turbo', 'XI'] },
  { id: 189, name: 'Wiesmann', models: ['MF3', 'MF4', 'GT'] },
  { id: 190, name: 'Xin Kai', models: ['SR-V', 'SUV9'] },
  { id: 191, name: 'Zastava', models: ['Yugo 45', 'Yugo Florida', 'Yugo Koral', 'Yugo Skala'] },
  { id: 192, name: 'Zotye', models: ['SR7', 'T700', 'Z100', 'Z500', 'Z300'] },
  { id: 193, name: 'ZX', models: ['Grand Tiger', 'Landmark', 'Admiral', 'Terralord', 'JOYEAR'] },
  { id: 280, name: 'Ultima', models: ['Evolution', 'GTR'] },
  { id: 282, name: 'Hawtai', models: ['Boliger', 'Shuttle', 'Lusheng E80'] },
  { id: 284, name: 'Renaissance', models: ['RS1', 'RS2'] },
]
